web/shop/urls.py
from django.conf.urls import url
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = 'shop'

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list,
        name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
]
urlpatterns += staticfiles_urlpatterns()

web/web/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    url(r'^', include('shop.urls', namespace='shop')),
]

web/models.py
from flask_sqlalchemy import SQLAlchemy
from web import db
from flask_login import LoginManager, UserMixin


class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(200), nullable=False)
    password = db.Column(db.String(200), nullable=False)

    def __repr__(self):
        return self.name


class Category(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(200), nullable=False)
    items = db.relationship('Item', backref='category', lazy=True)

    def __repr__(self):
        return self.name

    def all(self):
        return [self.id, self.name]


class Item(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    category_id = db.Column(db.Integer, db.ForeignKey('category.id'), nullable=True)
    title = db.Column(db.String(100), nullable=False)
    price = db.Column(db.Integer, nullable=False)
    isActive = db.Column(db.Boolean, default=True)
    text = db.Column(db.Text, nullable=False)
    first_image = db.Column(db.String(200), nullable=False)
    second_image = db.Column(db.String(200), nullable=True)
    value = db.Column(db.Integer, nullable=False)


    def __repr__(self):
        return self.title

    def all(self):
        return [self.id, self.category_id, self.title, self.price, self.isActive, self.value, self.text, self.first_image,
                self.second_image]

web/shop/models.py
from django.db import models

from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товар'
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

web/forms.py
from flask import session
from flask_wtf import FlaskForm
from flask_wtf.file import FileField
from wtforms import StringField, SubmitField, TextAreaField, BooleanField, PasswordField, SelectField, IntegerField, \
    RadioField
from wtforms.validators import DataRequired, Optional
from wtforms_components import EmailField

from models import Category, Item
import phonenumbers


def cost2cart(cost):
    if cost != 0:
        return f'  {cost}₽'
    else:
        return ''


def cart2cost(cart):
    return int(cart[:-1].lstrip())


def additemtocart(id, amount):
    print(session['cart'])
    if 'cart' not in session:
        session['cart'] = []
    session['cart'].append([id, amount])
    session.modified = True
    print(session['cart'])
    return session

def deletefromcart(id):
    if 'cart' not in session:
        session['cart'] = []
    for i in range(len(session['cart'])):
        if session['cart'][i][0] == id:
            session['cart'].pop(i)
            break
    session.modified = True
    print(session['cart'])
    return session


def deletecart():
    session['cart'] = []


def get_cart():
    cart = {}
    for id, amount in session['cart']:
        if id not in cart:
            cart[id] = 0
        cart[id] += amount
    return cart


def checkcart():
    cart = get_cart()
    for id in cart:
        amount = int(Item.query.get(id).value)
        if cart[id] > amount:
            session['cart'] = [[id_, amount] for id_, amount in session['cart'] if id != id_]


def from_cart_to_list():
    res = []
    cart = get_cart()
    for id in cart:
        res.append([Item.query.get(id), cart[id]])
    return res


def sum_cart():
    if 'cart' not in session:
        session['cart'] = []
    price = 0
    for id, amount in session['cart']:
        price += int(Item.query.get(id).price) * int(amount)
    return price


class LoginForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired()])
    submit = SubmitField()


class ItemForm(FlaskForm):
    name = StringField("Название")
    first_image = FileField('Первое фото', validators=[Optional()])

    second_image = FileField('Опционально: дополнительное фото', validators=[Optional()])

    categories = [(i.id, i.name) for i in Category.query.all()]

    category = SelectField('Категория', choices=categories)
    price = IntegerField('Цена')
    is_active = BooleanField('В наличии')
    text = TextAreaField('Описание')
    value = IntegerField('Количество товара')

    submit = SubmitField('Сохранить')



class CheckoutForm(FlaskForm):
    name = StringField("Имя")
    email = EmailField("E-mail")
    phone = StringField('Телефон', validators=[DataRequired()])

    def validate_phone(self, phone):
        try:
            p = phonenumbers.parse(phone.data)
            if not phonenumbers.is_valid_number(p):
                raise ValueError()
        except (phonenumbers.phonenumberutil.NumberParseException, ValueError):
            raise ValueError('Invalid phone number')

    submit = SubmitField('Отправить')


class CategoryForm(FlaskForm):
    name = StringField("Название")
    submit = SubmitField('Сохранить')

web/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, Category
from django.http import HttpResponse


def index(request):
    return render(request, 'shop/home.html')

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    return render(request,
                  'shop/product/detail.html',
                  {'product': product})

web/templates/about.html
{% extends 'base.html' %}

{% block title %}
<title>Про магазин</title>
{% endblock %}

{% block body %}
<div class="container">
    <h1>О магазине</h1>
    <p>"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem
        aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo
        enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos
        qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet,
        consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam
        quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam,
        nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse
        quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?"</p>
    <h3>Контакты:</h3>
    <p>+7(903)737-47-34</p>
    <p>г. Москва, пл. Журавлева, 10</p>

    <iframe frameborder="yes" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2243.576697357034!2d37.70308921582977!3d55.783223380561495!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46b535723b58fbd5%3A0x8d31e4b4a3edd839!2z0L_Quy4g0JbRg9GA0LDQstC70LXQstCwLCAxMCwg0JzQvtGB0LrQstCwLCAxMDcwMjM!5e0!3m2!1sru!2sru!4v1618503847412!5m2!1sru!2sru" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
</div>
{% endblock %}

web/templates/admin.html
{% extends 'base.html' %}

{% block title%}
<title>Админка</title>
{% endblock%}
{% block body %}


<h3>Привет, {{ current_user.username }}!</h3>

<p><a href="{{ url_for('listcategories') }}">Категории</a></p>
<p><a href="{{ url_for('listitems') }}">Товары</a></p>


<p><a href="{{ url_for('logout') }}">Logout</a></p>

{% endblock %}

web/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Bootstrap 4 Navbar with Logo Image</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://yastatic.net/share2/share.js"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/style.css') }}">


    {% block title %}{% endblock%}

<body>
<div class="bs-menu">
    <nav class="navbar navbar-expand-md navbar-light bg-primary">
        <a href="#" class="navbar-brand">
            <img src="{{ url_for('static', filename='img/snow.svg') }}" height="35" alt="CoolBrand">
        </a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav">
                <a href="{{ url_for('index') }}" class="nav-item nav-link active text-white">Главная</a>
                <a href="{{ url_for('about') }}" class="nav-item nav-link text-white">О нас</a>
            </div>
            <div class="navbar-nav ml-auto">
                <a href="{{ url_for('cart') }}" class="nav-item nav-link text-white"><i class="fa fa-shopping-cart" style="font-size: 24px" aria-hidden="true"></i>{{ cost }}</a>
            </div>
        </div>
    </nav>
</div>
<div class="content">
    {% block body %}
    {% endblock %}
</div>
<footer class="text-center text-white bg-primary">
  <div class="text-center p-3">
    © 2021 Copyright:
    <a class="text-white" href="https://gigandev.ru/">Eugene Degtyarev</a>
  </div>
</footer>
</body>
</html>

web/templates/cart.html
{% extends 'base.html' %}
{% block body %}
<!--Section: Block Content-->
<section class="shopping-cart dark">
    <div class="container">
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">Корзина</h1>
            <p class="lead">Здесь все товары, которые вы выбрали</p>
        </div>
        {% if items %}
        <div class="content">
            <div class="row">
                <div class="col-md-12 col-lg-8">
                    <div class="items">
                        {% for item, amount in items %}
                        <div class="product-cart product">
                            <div class="row">
                                <div class="col-md-3">
                                    <a href="{{ url_for('product', id=item.id) }}"><img
                                            src="/static/img/{{ item.first_image }}" width="200px" height="200px"></a>
                                </div>
                                <div class="col-md-8">
                                    <div class="info">
                                        <div class="row">
                                            <div class="col-md-5 product-name">
                                                <div class="product-name">
                                                    <a href="{{ url_for('product', id=item.id) }}">{{ item.title }}</a>
                                                    <div class="product-info">
                                                        <label for="quantity">Количество: {{ amount }}</label>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-4 price">
                                                <span>{{ item.price }}₽</span>
                                                <a href="{{ url_for('deleteitemfromcart', id=item.id) }}"><i class="fa fa-times" aria-hidden="true"></i></a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-md-12 col-lg-4">
                    <div class="summary">
                        <h3>Сумма</h3>
                        <div class="summary-item"><span class="text">Всего:</span><span class="price" style="font-weight: 600">{{ sum_ }}₽</span>
                        </div>
                        <form action="{{ url_for('order') }}">
                            <button type="submit" class="btn btn-primary btn-lg btn-block">К оформлению заказа</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
</section>
{% endblock %}

web/templates/checkout.html
{% extends 'base.html' %}


{% block body %}
{% for category, message in get_flashed_messages(with_categories=true) %}
<spam class="{{ category }}">{{ message }}</spam>
{% endfor %}
<div class="form-group">
    <form action="" method="post">
        {{ form.csrf_token }}
        <div class="container">
            {{ form.username.label() }}
            <br>
            {{ form.username(class_='form-control') }}
            <br>

            {% if form.username.errors %}
            {% for error in form.username.errors %}
            {{ error }}
            {% endfor %}
            {% endif %}
            <br>
            {{ form.password.label() }}
            <br>
            {{ form.password(class_='form-control') }}
            <br>
            {% if form.password.errors %}
            {% for error in form.password.errors %}
            {{ error }}
            {% endfor %}
            {% endif %}
            <br>
            {{ form.submit() }}
            <br>
        </div>
    </form>
</div>
    {% endblock %}

web/templates/create.html
{% extends 'base.html' %}


{% block body %}
<form action="" method="post" enctype="multipart/form-data">
    {{ form.csrf_token }}
    <div class="container">
        {% for field in form if field.name != 'csrf_token' %}
            {{ field.label() }}
            <br>
            {% if 'image' in field.name %}
            {{ field(class_='form-control-file') }}
            {% if 'second' in field.name %}
            <img src="/static/img/{{ images.split(', ')[0] }}" width="200px" alt="Перезагрузи страничку или перезалей фотку">
                {% for img in images.split(', ')[1:] %}
                <img src="/static/img/{{ img }}" width="200px" alt="Перезагрузи страничку или перезалей фотку">
                <a href="{{ url_for('deletephoto', id=id, photo=img) }}">Удалить</a>
                {% endfor %}
            {% endif %}
            {% else %}
            {{ field(class_='form-control') }}
            {% endif %}
            <br>
            <br>
        {% endfor %}
    </div>
</form>
{{ message }}
    {% if mode == 0 %}
    <p><a href="{{ url_for('listitems') }}">Назад</a></p>
    {% else %}
    <p><a href="{{ url_for('listcategories', id=last_id) }}">Назад</a></p>
    {% endif %}

{% endblock %}

web/templates/index.html
{% extends 'base.html' %}

{% block title %}
<title>Онлайн магазин</title>
{% endblock %}

{% block body %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center anim-show-fast">
    <h1 class="display-4">Shopartglass</h1>
    <p class="lead">Добро пожаловать в наш магазин!</p>
</div>


<div class="container content anim-show-slow">
    <div class="row" style="background-color: white; padding: 3px; padding-top: 25px;">
        <div class="col-md-4">
            <div class="list-group text-center">
                <a href="{{ url_for('index') }}"
                   class="text-decoration-none all_cat list-group-item">Все товары</a>
                {% for category in categories %}
                <a href="{{ url_for('index', category=category.id) }}" class="text-decoration-none cat list-group-item">{{
                    category }}</a>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-8 products">
            {% for item in items %}
            {% if loop.index0 % 3 == 0 %}
            {% set iter = loop %}
            <div class="row">
                {% for i in range(3) %}
                {% if iter.index0+i < items|length %}
                <div class="col-sm-4">
                    <div class="product product-index">
                        <div class="product-img center-block">
                            <a href="{{ url_for('product', id=items[iter.index0+i].id) }}"><img src="/static/img/{{ items[iter.index0+i].first_image }}" width="150px"
                                             height="150px"
                                             alt=""></a>
                        </div>
                        <p class="product-title">
                            <a href="{{ url_for('product', id=items[iter.index0+i].id) }}">{{ items[iter.index0+i].title }}</a>
                        </p>
                        <p class="product-desc">{{ items[iter.index0+i].text }}</p>
                        <p class="product-price">{{ items[iter.index0+i].price }}₽</p>
                    </div>
                </div>
                {% endif %}
                {% endfor %}
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>


    {% endblock %}

web/templates/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
    <div id="sidebar">
        <h3>Categories</h3>
        <ul>
            <li {% if not category %}class="selected"{% endif %}>
                <a href="{% url "shop:product_list" %}">All</a>
            </li>
            {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div id="main" class="product-list">
        <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
        {% for product in products %}
            <div class="item">
                <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                </a>
                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
                ${{ product.price }}
            </div>
        {% endfor %}
    </div>
{% endblock %}

web/templates/login.html
{% extends 'base.html' %}


{% block body %}
{% for category, message in get_flashed_messages(with_categories=true) %}
<spam class="{{ category }}">{{ message }}</spam>
{% endfor %}
<div class="form-group">
    <form action="" method="post">
        {{ form.csrf_token }}
        <div class="container">
            {{ form.username.label() }}
            <br>
            {{ form.username(class_='form-control') }}
            <br>

            {% if form.username.errors %}
            {% for error in form.username.errors %}
            {{ error }}
            {% endfor %}
            {% endif %}
            <br>
            {{ form.password.label() }}
            <br>
            {{ form.password(class_='form-control') }}
            <br>
            {% if form.password.errors %}
            {% for error in form.password.errors %}
            {{ error }}
            {% endfor %}
            {% endif %}
            <br>
            {{ form.submit() }}
            <br>
        </div>
    </form>
</div>
    {% endblock %}

web/templates/order.html
{% extends 'base.html' %}
{% block body %}
<!--Section: Block Content-->
<form action="" method="post" enctype="multipart/form-data">
    {{ form.csrf_token }}
    <div class="container">
        {% for field in form if field.name != 'csrf_token' %}
            {% if 'submit' not in field.name %}
            {{ field.label() }}*
            {% endif %}
            <br>
            {{ field(class_='form-control') }}
            <br>
            <br>
        {% endfor %}
    </div>
</form>
{{ message }}
<div class="container"><h3>Мы скоро вам перезвоним и уточним детали заказа!</h3></div>

{% endblock %}

web/templates/product.html
{% extends "base.html" %}

{% block body %}
<div class="container">

    <!--Section: Block Content-->
    <section class="my-5">

        <div class="row">
            <div class="col-md-5 mb-4 mb-md-0">
                <div id="carouselExampleIndicators" class="carousel slide" data-interval="false" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        {% for img in images.split(', ')[1:] %}
                        <li data-target="#carouselExampleIndicators" data-slide-to="{{ loop.index }}"></li>
                        {% endfor %}
                    </ol>
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img class="d-block w-100" src="/static/img/{{ item.first_image }}" alt="Первый слайд">
                        </div>
                        {% if item.second_image %}
                        {% for img in images.split(', ')[1:] %}
                        <div class="carousel-item">
                            <img class="d-block w-100" src="/static/img/{{ img }}" alt="Второй слайд">
                        </div>
                        {% endfor %}
                        {% endif %}
                    </div>
                    {% if item.second_image %}
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                    {% endif %}
                </div>


            </div>
            <div class="col-md-7">

                <h5>{{ item.title }}</h5>
                <p><span class="mr-1"><strong>{{ item.price }}р.</strong></span></p>
                <p class="pt-1">{{ item.text }}</p>
                <hr>
                <form action="" method="post">
                    <div class="table-responsive mb-2">
                        <table class="table table-sm table-borderless">
                            <tbody>
                            <tr>
                                <td class="pl-0 pb-0 w-25">Количество</td>
                            </tr>
                            <tr>
                                <td class="pl-0">
                                    <div class="def-number-input number-input safari_only mb-0">
                                        <input class="quantity" min="1" max="{{ item.value }}" name="amount" value="1"
                                               type="number">
                                    </div>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                    <button type="submit" class="btn btn-primary btn-md mr-1 mb-2"><i
                            class="fa fa-shopping-cart pr-2"></i>Add to cart
                    </button>
                </form>
                <br>
                Поделитесь товаром в социальных сетях:

                <div class="ya-share2" style="padding-top: 15px" data-size="l" data-curtain data-shape="round"
                     data-services="vkontakte,facebook,odnoklassniki,telegram,viber,whatsapp"></div>
                </form>
                <hr>
                <a href="#">Политика конфидециальности</a>
            </div>
        </div>

    </section>
</div>
{% endblock %}

web/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Bootstrap 4 Navbar with Logo Image</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</head>
<style>
    bs-menu {
        background-color: gray;
    }
</style>
<body>
<div class="bs-menu">
    <nav class="navbar navbar-expand-md navbar-light bg-primary">
        <a href="#" class="navbar-brand">
            <img src="{% static "android.svg" %}" height="35" alt="CoolBrand">
        </a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav">
                <a href="#" class="nav-item nav-link active text-white">Главная</a>
                <a href="#" class="nav-item nav-link text-white">Магазин</a>
                <a href="#" class="nav-item nav-link text-white">О нас</a>
            </div>
            <div class="navbar-nav ml-auto">
                <a href="#" class="nav-item nav-link text-white">Войти</a>
            </div>
        </div>
    </nav>
</div>
<div class="content">
    {% block content %}
    {% endblock %}
</div>
<footer class="text-center text-white bg-primary">
  <div class="text-center p-3">
    © 2020 Copyright:
    <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
</footer>
</body>
</html>

web/templates/success.html
{% extends 'base.html' %}

{% block title %}
<title>Онлайн магазин</title>
{% endblock %}

{% block body %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center anim-show-fast">
    <h1 class="display-4">Скоро мы вам перезвоним!</h1>
</div>
{% endblock %}

web/templates/table.html
{% extends 'base.html' %}
{% block body %}

{% if mode == 0 %}
<p style="margin: 5px"><a href="{{ url_for('edititem', id=last_id) }}">Новый товар  <i class="fa fa-plus" aria-hidden="true"></i></a></p>
{% else %}
<p style="margin: 5px"><a href="{{ url_for('editcategory', id=last_id) }}">Новая категория  <i class="fa fa-plus" aria-hidden="true"></i></a></p>
{% endif %}
<div class="sdf">

    <table class="table myTable">
        <tbody>
        {% for item in data %}
        {% if loop.index0 == 0 %}
        <thead class="thead-dark">
        <tr>
            <th scope="col">Удалить</th>
            {% for value in item %}
            <th scope="col">{{ value }}</th>
            {% endfor %}
        </tr>
        </thead>
        {% else %}
        <tr>
            {% if mode == 0 %}
            <td><a href="{{ url_for('deleteitem', id=item[0]) }}"><i class="fa fa-times" aria-hidden="true"></i></a>
            {% else %}
            <td><a href="{{ url_for('deletecategory', id=item[0]) }}"><i class="fa fa-times" aria-hidden="true"></i></a>
            {% endif %}

            </td>
            {% for value in item %}
            {% if loop.index0 < 7 %}
            {% if mode == 0 %}
            <td><a style='color: #000' href="{{ url_for('edititem', id=item[0]) }}">{{ value }}</a></td>
            {% else %}
            <td><a style='color: #000' href="{{ url_for('editcategory', id=item[0]) }}">{{ value }}</a></td>
            {% endif %}
            {% else %}
            <td><img src="/static/img/{{ value }}" width="100px" alt=""></td>
            {% endif %}
            {% endfor %}
        </tr>
        {% endif %}
        {% endfor %}
        </tbody>
    </table>
</div>
<p style="margin: 5px"><a href="{{ url_for('admin') }}"><i class="fa fa-undo" aria-hidden="true"></i></a></p>

{% endblock %}